[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 800
via_ir = false
solc_version = '0.8.26'
evm_version = "cancun"
ffi = true